// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9tY6_EWn2jtnGzCj6QiZjeopWVu_bWo',
    appId: '1:826369760407:web:798a1017c60461dfa81dd2',
    messagingSenderId: '826369760407',
    projectId: 'chatapp-bf45a',
    authDomain: 'chatapp-bf45a.firebaseapp.com',
    storageBucket: 'chatapp-bf45a.appspot.com',
    measurementId: 'G-2DP0N6QD77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlE8kX-WP7bEl6VgjH1hgzW1g4nMuv1NM',
    appId: '1:826369760407:android:4ac58d1e79af4bdca81dd2',
    messagingSenderId: '826369760407',
    projectId: 'chatapp-bf45a',
    storageBucket: 'chatapp-bf45a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiidN0MKmmFgJkMzp8npb4f2u8Oat_MU',
    appId: '1:826369760407:ios:b00bb470b7819148a81dd2',
    messagingSenderId: '826369760407',
    projectId: 'chatapp-bf45a',
    storageBucket: 'chatapp-bf45a.appspot.com',
    iosClientId: '826369760407-1nqgnl3s1upqtq8stl89h5jjfq0iivvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAiidN0MKmmFgJkMzp8npb4f2u8Oat_MU',
    appId: '1:826369760407:ios:b00bb470b7819148a81dd2',
    messagingSenderId: '826369760407',
    projectId: 'chatapp-bf45a',
    storageBucket: 'chatapp-bf45a.appspot.com',
    iosClientId: '826369760407-1nqgnl3s1upqtq8stl89h5jjfq0iivvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
